// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_2.Models;

namespace TEST_2_NET_5_proper.Migrations
{
    [DbContext(typeof(s20353Context))]
    partial class s20353ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test_2.Models.CityDict", b =>
                {
                    b.Property<int>("IdCityDict")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdCityDict");

                    b.ToTable("CityDict", "Test_2");

                    b.HasData(
                        new
                        {
                            IdCityDict = 1,
                            City = "Warszawa"
                        },
                        new
                        {
                            IdCityDict = 2,
                            City = "Tokyo"
                        });
                });

            modelBuilder.Entity("Test_2.Models.Flight", b =>
                {
                    b.Property<int>("IdFlight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FlightDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCityDict")
                        .HasColumnType("int");

                    b.Property<int>("IdPlane")
                        .HasColumnType("int");

                    b.HasKey("IdFlight");

                    b.HasIndex("IdCityDict");

                    b.HasIndex("IdPlane");

                    b.ToTable("Flight", "Test_2");

                    b.HasData(
                        new
                        {
                            IdFlight = 1,
                            FlightDate = new DateTime(2022, 6, 9, 15, 5, 0, 379, DateTimeKind.Local).AddTicks(6889),
                            IdCityDict = 1,
                            IdPlane = 1
                        },
                        new
                        {
                            IdFlight = 2,
                            Comments = "generic comment",
                            FlightDate = new DateTime(2022, 6, 9, 15, 5, 0, 381, DateTimeKind.Local).AddTicks(2177),
                            IdCityDict = 2,
                            IdPlane = 2
                        });
                });

            modelBuilder.Entity("Test_2.Models.Flight_Passenger", b =>
                {
                    b.Property<int>("IdFlight")
                        .HasColumnType("int");

                    b.Property<int>("IdPassenger")
                        .HasColumnType("int");

                    b.HasKey("IdFlight");

                    b.HasIndex("IdPassenger");

                    b.ToTable("Firefighter_Action", "Test_2");

                    b.HasData(
                        new
                        {
                            IdFlight = 1,
                            IdPassenger = 1
                        },
                        new
                        {
                            IdFlight = 2,
                            IdPassenger = 2
                        });
                });

            modelBuilder.Entity("Test_2.Models.Passenger", b =>
                {
                    b.Property<int>("IdPassenger")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PassportNum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdPassenger");

                    b.ToTable("Passenger", "Test_2");

                    b.HasData(
                        new
                        {
                            IdPassenger = 1,
                            FirstName = "John",
                            LastName = "Doe",
                            PassportNum = "ABC123"
                        },
                        new
                        {
                            IdPassenger = 2,
                            FirstName = "Jane",
                            LastName = "Smith",
                            PassportNum = "DEF456"
                        });
                });

            modelBuilder.Entity("Test_2.Models.Plane", b =>
                {
                    b.Property<int>("IdPlane")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxSeats")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPlane");

                    b.ToTable("Plane", "Test_2");

                    b.HasData(
                        new
                        {
                            IdPlane = 1,
                            MaxSeats = 50,
                            Name = "FirstPlane"
                        },
                        new
                        {
                            IdPlane = 2,
                            MaxSeats = 100,
                            Name = "SecondPlane"
                        });
                });

            modelBuilder.Entity("Test_2.Models.Flight", b =>
                {
                    b.HasOne("Test_2.Models.CityDict", "CityDict")
                        .WithMany("Flights")
                        .HasForeignKey("IdCityDict")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test_2.Models.Plane", "Plane")
                        .WithMany("Flights")
                        .HasForeignKey("IdPlane")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CityDict");

                    b.Navigation("Plane");
                });

            modelBuilder.Entity("Test_2.Models.Flight_Passenger", b =>
                {
                    b.HasOne("Test_2.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("IdFlight")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test_2.Models.Passenger", "Passenger")
                        .WithMany("Flight_Passengers")
                        .HasForeignKey("IdPassenger")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Test_2.Models.CityDict", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Test_2.Models.Passenger", b =>
                {
                    b.Navigation("Flight_Passengers");
                });

            modelBuilder.Entity("Test_2.Models.Plane", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
